# Generated by Django 4.2.1 on 2023-05-23 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0002_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="emotion",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
