# Generated by Django 4.2.1 on 2023-05-23 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_uploadedfile_emotion_uploadedfile_user_delete_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="uploaded_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
